### ISSUE TITLE
Не работает когда запущены 2 бота

### ISSUE THREAD

**Issue by cxemnet** [TomBishop-Auto/A-Bot_GUI#1]
Использую на 1 ПК два разных бота BTC и USDT. Проги лежат каждая в соотв. папке бота. Но работает только одна. Вторую когда запускаю, ставлю флажок соответствующий, она бота и окно не видит

**Comment by TomBishop-Auto** [comment]
Не соблюдена инструкция работы с программой. Зайдите в телеграмм канал бота, там будет проще Вам помочь.
